### PR TITLE
fixrule(`element_orientation_unlocked, img_alt_valid, aria_accessiblename_exists, img_alt_null`): fix issues related to the rules

### LINKED ISSUE #1938: ACT 46ca7f: Element marked as decorative is not exposed - Expected failed, but returned passed
The Checker is passing this ACT testcase, but ACT says it is a failed example:

ACT ruleID [46ca7f](https://www.w3.org/WAI/standards-guidelines/act/rules/46ca7f): [Element marked as decorative is not exposed](https://www.w3.org/WAI/standards-guidelines/act/implementations/equal-access/#breakdown-46ca7f)

> **_Failed Example 2_** [Open in a new tab](https://w3.org/WAI/content-assets/wcag-act-rules/testcases/46ca7f/96c1f58088f1e32c965f38ddc50d4b88f6a0f022.html)
> This img element is [marked as decorative](https://www.w3.org/WAI/standards-guidelines/act/rules/46ca7f/#marked-as-decorative) through its empty alt attribute but has a non-empty aria-labelledby attribute causing it to be [included in the accessibility tree](https://www.w3.org/WAI/standards-guidelines/act/rules/46ca7f/#included-in-the-accessibility-tree) with its [implicit role](https://www.w3.org/WAI/standards-guidelines/act/rules/46ca7f/#implicit-role) of img.
> ```
>  
> <span hidden id="label">W3C logo</span>
> ```

Checker ACT results [act-report-v2 2024-06-17.txt](https://ibm.box.com/s/or6i901ke3etyv5xoo5e61yynx6xem77) : Expected failed, but returned earl:passed for ACT 46ca7f

Checker rule: [aria_attribute_valid]() returns pass
```
    "ruleId": "aria_attribute_valid",
    "reasonId": "Pass",
    "message": "ARIA attributes are valid for the element and ARIA role",
```
[help - aria_attribute_valid](https://able.ibm.com/rules/archives/preview/doc/en-US/aria_attribute_valid.html#%7B%22message%22%3A%22ARIA%20attributes%20are%20valid%20for%20the%20element%20and%20ARIA%20role%22%2C%22snippet%22%3A%22%3Cimg%20aria-labelledby%3D%5C%22label%5C%22%20alt%3D%5C%22%5C%22%20src%3D%5C%22%2FWAI%2Fcontent-assets%2Fwcag-act-rules%2Ftest-assets%2Fshared%2Fw3c-logo.png%5C%22%3E%22%2C%22value%22%3A%5B%22VIOLATION%22%2C%22PASS%22%5D%2C%22reasonId%22%3A%22Pass%22%2C%22ruleId%22%3A%22aria_attribute_valid%22%2C%22msgArgs%22%3A%5B%22aria-labelledby%22%2C%22img%22%2C%22img%22%5D%7D)

### LINKED ISSUE #1958: ACT b33eff: Checker rule `element_orientation_unlocked` marks failed test case #4 inapplicable
The Checker is marking an ACT proposed rule `b33eff` test case # 4 as inapplicable, but ACT says it is a failed example.

Checker `element_orientation_unlocked` covers 11 of 12 test cases. Failed test 4 is incorrectly marked as inapplicable.
Checker source for [element_orientation_unlocked](https://github.com/IBMa/equal-access/blob/master/accessibility-checker-engine/src/v4/rules/element_orientation_unlocked.ts)

ACT ruleID [b33eff](https://www.w3.org/WAI/standards-guidelines/act/rules/b33eff/proposed/) 
[Checker implementation report](https://www.w3.org/WAI/standards-guidelines/act/implementations/equal-access/#breakdown-b33eff)
[ACT test case explanations](https://www.w3.org/WAI/standards-guidelines/act/rules/b33eff/proposed/#test-cases)

> Failed Example 4 [Open in a new tab](https://w3.org/WAI/content-assets/wcag-act-rules/testcases/b33eff/8f341a73c698daf157613c32a521878ed5aa7310.html)
A page where the CSS [rotate](https://www.w3.org/TR/css-transforms-2/#individual-transforms) property has a 90 degree rotation conditionally applied on the [orientation](https://www.w3.org/TR/css3-mediaqueries/#orientation) [media feature](https://www.w3.org/TR/css3-mediaqueries/#media1) which restricts the element to landscape orientation.
```
<html lang="en">
	<head>
		<title>Page with some content</title>
		<style>
			@media (orientation: portrait) {
				html {
					rotate: 90deg;
					width: min(100vw, 100vh);
					height: min(100vw, 100vh);
				}
			}
		</style>
	</head>
	<body>
		Page Content
	</body>
</html>
```

## Checker ACT results [act-report-v2 2024.txt](https://ibm.box.com/s/or6i901ke3etyv5xoo5e61yynx6xem77) : 
- [Failed Example 4](https://www.w3.org/WAI/content-assets/wcag-act-rules/testcases/b33eff/8f341a73c698daf157613c32a521878ed5aa7310.html) test case tested & reported in log:
- `Expected failed, but returned earl:inapplicable`

Checker rule: [element_orientation_unlocked](https://github.com/IBMa/equal-access/blob/master/accessibility-checker-engine/src/v4/rules/element_orientation_unlocked.ts) is not triggered on test case 4 ACT results logs the following:
```
   Failures: []
    Review: []
    Pass: []
    All: [
      "html_skipnav_exists:Potential_1:POTENTIAL",
      "style_highcontrast_visible:Manual_1:MANUAL",
      "skip_main_exists:Fail_1:FAIL"
```

## Supporting notes and details
- [x] No change to Help needed.
- [ACT Master 2024.xlsx](https://ibm.box.com/s/evec4kfixgzjw8tmghnr9f13xxw99e33)

### LINKED ISSUE #2013: ACT: Add fail reason to `img_alt_null` for conflicts in attributes and map to ACT rule 46ca7f
In the ACT test case below the ARIA label does go into the accessibility tree in Chrome and FF, so the `accessible name` is **_not_** empty. However, the developer may be confused because the `alt=""` was added in their source code, perhaps thinking it would mark the `img` as decorative, but it wasn't due to the `alt` attribute being ignored/overridden by the `aria` attribute because of the [accessible name calculation](https://www.w3.org/TR/html-aam-1.0/#img-element-accessible-name-computation) spec for browsers. 

> **_Failed Example 2_** [Open in a new tab](https://w3.org/WAI/content-assets/wcag-act-rules/testcases/46ca7f/96c1f58088f1e32c965f38ddc50d4b88f6a0f022.html)
> This img element is [marked as decorative](https://www.w3.org/WAI/standards-guidelines/act/rules/46ca7f/#marked-as-decorative) through its empty alt attribute but has a non-empty aria-labelledby attribute causing it to be [included in the accessibility tree](https://www.w3.org/WAI/standards-guidelines/act/rules/46ca7f/#included-in-the-accessibility-tree) with its [implicit role](https://www.w3.org/WAI/standards-guidelines/act/rules/46ca7f/#implicit-role) of img.
> ```
>  
> <span hidden id="label">W3C logo</span>
> ```

However, the Checker should be a **_new_** warning or recommendation notifying the developer of the contradiction (this issue). The Checker should add a new fail reason code in the [image_alt_null](https://github.com/IBMa/equal-access/blob/master/accessibility-checker-engine/src/v4/rules/img_alt_null.ts) (rule source code). 

There is another issue against ACT to clarify/ask why the Failed 2 above is a valid fail test case for ACT ruleID [46ca7f](https://www.w3.org/WAI/standards-guidelines/act/rules/46ca7f): [Element marked as decorative is not exposed](https://www.w3.org/WAI/standards-guidelines/act/implementations/equal-access/#breakdown-46ca7f) - see https://github.com/w3c/wcag-act-rules/issues/295

### PR DESCRIPTION
**Pull request by shunguoy**
* Rule bug: **element_orientation_unlocked, img_alt_valid, aria_accessiblename_exists**

### This PR is related to the following issue(s): 

- Fixes #1958
- Fixes #2013 
- Fixes #1938 

### Testing reference: 

- test case for #1958: test/v2/checker/accessibility/rules/element_orientation_unlocked_ruleunit/act-fail4.html
- After the fix, an additional violation appears with the message: "The element <html> is restricted to either landscape or portrait orientation using CSS transform property".
- test case for #2013: test/v2/checker/accessibility/rules/img_alt_null_ruleunit/Img-alt-arialabel.html
- After the fix, an additional NR appears with the message : "The image 'alt' attribute is empty, but the 'aria' label is not empty and overrides the 'alt' attribute".
- 
### I have conducted the following for this PR: 
- [x] I validated this code in Chrome and FF 
- [x] I validated this fix in my local env
- [x] I provided details for testing
- [x] This PR has been reviewed and is ready for test  
- [x] I understand that the title of this PR will be used for the next release notes.

### CODE REVIEW

**Review by tombrunet — APPROVED** [review]

File: accessibility-checker-engine/src/v4/rules/aria_img_labelled.ts [hunk 1]
```diff
@@ -11,14 +11,13 @@
...
-import { Rule, RuleResult, RuleFail, RuleContext, RulePotential, RuleManual, RulePass, RuleContextHierarchy } from "../api/IRule";
-import { eRulePolicy, eToolkitLevel } from "../api/IRule";
+import { Rule, RuleResult, RuleFail, RuleContext, RulePass, RuleContextHierarchy } from "../api/IRule";
 import { RPTUtil } from "../../v2/checker/accessibility/util/legacy";
 import { VisUtil } from "../../v2/dom/VisUtil";
 
 export let aria_img_labelled: Rule = {
     id: "aria_img_labelled",
-    context: "aria:img",
+    context: "aria:img, aria:image",
```
Comment (tombrunet) [inline accessibility-checker-engine/src/v4/rules/aria_img_labelled.ts:20]: The ARIA role is `img`. I don't understand what `image` is doing here?

Comment (tombrunet) [reply accessibility-checker-engine/src/v4/rules/aria_img_labelled.ts:20]: Apparently `image` is an ARIA 1.3 synonum for `img`.

**Review by tombrunet — APPROVED** [review]
