### PR TITLE
fix(extension): adjust hidden counts

### LINKED ISSUE #1882: [BUG]: Hidden counting error between current scan report and chrome local storage
Example: Here I caused the error to happen by hiding all the recommendations (there are 6) then removing two of the associated elements so that there are actually 4 left. However, the storage still thinks there are 6.

### PR DESCRIPTION
**Pull request by drjoho**
fixes #1882 

### Testing reference: 
- 
Eric see me for testing

### I have conducted the following for this PR: 
- [x] I validated this code in Chrome and FF 
- [x] I validated this fix in my local env
- [x] I provided details for testing
- [ ] This PR has been reviewed and is ready for test  
- [x] I understand that the title of this PR will be used for the next release notes.

### CODE REVIEW

File: accessibility-checker-extension/src/ts/devtools/components/scanSection.tsx [hunk 1]
```diff
@@ -293,6 +294,7 @@ export class ScanSection extends React.Component<{}, ScanSectionState> {
         }
         if (reportIssues) {
             filterCounts = this.getCounts(reportIssues);
+            console.log("scan section filterCounts = ",filterCounts);
```
Comment (tombrunet) [inline accessibility-checker-extension/src/ts/devtools/components/scanSection.tsx:297]:
```suggestion
```

**Review by tombrunet — CHANGES_REQUESTED** [review]

**Review by tombrunet — APPROVED** [review]

**Review by tombrunet — APPROVED** [review]

**Comment by ErickRenteria** [comment]
validated
